sudo: required
serivces:
  - docker

before_install:
  - docker build -t kaarelsirel/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kaarelsirel/react-test npm test

after_success:
  - docker build -t kaarelsirel/multi-client ./client
  - docker build -t kaarelsirel/multi-nginx ./nginx
  - docker build -t kaarelsirel/multi-server ./server
  - docker build -t kaarelsirel/multi-worker ./worker